# Generated by Django 6.0 on 2026-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_booking_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
